### ISSUE TITLE
correcting the naming of realizations of profile negotiation

### ISSUE THREAD

**Issue by agreiner** [w3c/dxwg#1160]
This is not really a new issue, but it's probably never been an issue on its own before. Can we get rid of the instances where header-based negotiation is called "http"? Query strings are part of http, too. Browsers use http, including headers. And query strings are as likely to be used programmatically as in a browser, so I would suggest we stick with header-based negotiation and query-string-based negotiation. Here I suspect you meant to refer to all the non-header-based approaches as a single entity. I'm not sure how best to refer to that, but maybe it would work to call it URL-based negotiation.

**Comment by nicholascar** [comment]
I'm ok with "HTTP Header" and "URI Query String Arguments" as naming for the two environments. That seems pretty unambiguous.

**Comment by kcoyle** [comment]
Note that the [IETF document](https://profilenegotiation.github.io/I-D-Profile-Negotiation/I-D-Profile-Negotiation) that parallels Conneg uses the term "HTTP header".

**Comment by nicholascar** [comment]
Addressed by PR https://github.com/w3c/dxwg/pull/1165 with the names "HTTP Header" and "URL Query String Arguments" used throughout.

**Comment by kcoyle** [comment]
@nicholascar I still see HTTP used alone in the introduction section. Can you leave this open as an editorial change so that can be fixed? Thanks.

**Comment by nicholascar** [comment]
Aaarrgh, I missed that one! I've created a tiny PR for it: https://github.com/w3c/dxwg/pull/1171

**Comment by nicholascar** [comment]
PR #1171 is merged so the remaining Issue has been addressed.
